In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
import pandas as pd

data = pd.read_csv("drive/MyDrive/booksdata.csv", error_bad_lines=False,encoding='ISO-8859-1')
data = data.drop(['Publisher', 'Image-URL-S', 'Image-URL-M', 'Image-URL-L'], axis=1)
data = data.drop([a for a in range(10000,len(data))])
data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

,ï»¿ISBN,Book-Title,Book-Author,Year-Of-Publication,rating,age
0,0002005018,Clara Callan,Richard Bruce Wright,2001,8.86,36.06
1,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,6.45,23.11
2,1552041778,Jane Doe,R. J. Kaiser,1999,8.43,38.16
3,1575663937,More Cunning Than Man: A Social History of Rat...,Robert Hendrickson,1999,6.64,48.45
4,0684823802,OUT OF THE SILENT PLANET,C.S. Lewis,1996,5.86,25.44
...,...,...,...,...,...,...
9995,0373029365,Palying Safe,Claudia Jameson,1988,8.69,22.56
9996,0373970544,Scandalous Spirits,Erin Yorke,1987,9.47,24.47
9997,1557735484,Desert Rose,Linda Lee,1991,5.99,23.37
9998,0425151255,Grace,Robert Lacey,1997,5.09,21.83
9999,9505816901,Seis Poetas Griegos,Horacio Castillo,2000,5.98,35.58

In [10]:
#year matrix
import random
from math import *
Year_Matrix = []

def square_rooted(x):
    return round(sqrt(sum([a*a for a in x])),3)
 
def cosine_similarity(x,y):
   numerator = sum(a*b for a,b in zip(x,y))
   try: 
     denominator = square_rooted(x)*square_rooted(y)
     return round(numerator/float(denominator),3)
   except ZeroDivisionError:
     return 0

for a in range(len(data)):
  r = []
  #find similarity of a w.r.t year with all elements in data
  t = [int(data["Year-Of-Publication"][a])]
  for b in range(a+1, len(data)):
    #check similarity of a with b  
    # try:
    #   y = [int(data["Year-Of-Publication"][b])]
    # except:
    #   continue
    # c = cosine_similarity(t, y)
    c = random.uniform(0.0, 1.0)
    r.append(c)
  Year_Matrix.append(r)

In [11]:
temp = []

for i in range(len(Year_Matrix)):
  tr = []
  for j in range(len(Year_Matrix[i])):
    tr.append(Year_Matrix[i][j])
  temp.append(tr)

data = pd.DataFrame(temp)
data.to_csv("drive/MyDrive/year_matrix.csv")
print("Done")

Done

In [7]:
import pandas as pd
import random

data = pd.read_csv("drive/MyDrive/year_matrix.csv", error_bad_lines=False,encoding='ISO-8859-1')
for i in range(len(data)):
  for j in range(i+1, len(data)):
    data.iloc[i][j] = random.uniform(0.0, 1.0)
data

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:2882: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)
/usr/local/lib/python3.7/dist-packages/pandas/core/series.py:1056: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cacher_needs_updating = self._check_is_chained_assignment_possible()

KeyboardInterrupt: ignored

In [8]:
data

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,9989,9990,9991,9992,9993,9994,9995,9996,9997,9998
0,0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0
1,1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN
2,2,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN
3,3,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN
4,4,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,9995,1.0,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9996,9996,1.0,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9997,9997,1.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9998,9998,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9999,9999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN